filter:
    paths: [src/*]
    excluded_paths: [test/*, vendor/*, bin/*, doc/*]
before_commands:
    - "composer update --prefer-source"
    - composer require --no-dev zendframework/zend-db:~2 --update-no-dev 
    - composer require --no-dev doctrine/dbal:~2 --update-no-dev 
    - composer require --no-dev illuminate/database:~5 --update-no-dev 
    
tools:
    external_code_coverage: 
        timeout: 600
    php_cpd:
        excluded_dirs: ["vendor", "test", "bin", "doc"]    
    php_pdepend:
        excluded_dirs: ["vendor", "test", "bin", "doc"]
    php_loc: 
        excluded_dirs: ["vendor", "test", "bin", "doc"]
    php_cs_fixer:
        config:
            level: psr2
    php_pdepend:
        enabled: true
        excluded_dirs: ["vendor", "test", "bin", "doc"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]   
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]            
    php_mess_detector: true
    php_hhvm: false
    sensiolabs_security_checker: true