filter:
    paths: [src/*]
    excluded_paths: [test/*, vendor/*, bin/*, doc/*]
before_commands:
    - "composer update --prefer-source"
tools:
    external_code_coverage: 
        timeout: 600
    php_cpd:
        excluded_dirs: ["vendor", "test", "bin", "doc"]    
    php_pdepend:
        excluded_dirs: ["vendor", "test", "bin", "doc"]
    php_loc: 
        excluded_dirs: ["vendor", "test", "bin", "doc"]
    php_cs_fixer:
        config:
            level: psr2
    php_pdepend:
        enabled: true
        excluded_dirs: ["vendor", "test", "bin", "doc"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]   
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]            
    php_mess_detector: true
    php_hhvm: false
    sensiolabs_security_checker: true