language: php
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - SEND_COVERAGE=true
    - php: 7
    - php: nightly
    - php: hhvm-3.12
    - php: hhvm-nightly
  allow_failures:
    - php: nightly

env:
    global:
        - SEND_COVERAGE=false

before_script:
  - mkdir -p test/logs
  - mkdir -p tests/tmp/cache 
  - mkdir -p build/logs
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_schema_db;" -u root
  - mysql -e "CREATE DATABASE phpunit_soluble_schema_db;" -u root
  - zcat test/data/mysql/schema.sql.gz | mysql -u root phpunit_soluble_schema_db
  - zcat test/data/mysql/data.sql.gz | mysql -u root phpunit_soluble_schema_db
  - mysql -e "SHOW DATABASES;" -u root
  - mysql -e "CONNECT phpunit_soluble_schema_db; SHOW TABLES;" -u root  
  - travis_retry composer self-update
  - travis_retry composer --prefer-source --dev install
script: 
  - ./vendor/bin/phpunit -v --coverage-clover=coverage.xml
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
