docs_dir: doc
site_dir: build/doc
pages:
    - index.md
    - { 'Contributing': CONTRIBUTING.md }
site_name: soluble-dbwrapper
site_description: "soluble-dbwrapper"
theme: readthedocs
#theme: bootstrap
#theme: united
repo_url: 'https://github.com/belgattitude/soluble-dbwrapper'
markdown_extensions:
    - toc:
        permalink: True
    - codehilite:
        linenums: False
        guess_lang: True
        #pygments_style: monokai
        #use_pygments: True
    